//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid playerActions = new Guid("ce29d5c9-199b-44ee-8edb-1b1d5cdcd0d0");
		public static readonly Guid PlayerMove = new Guid("cf39d053-69d1-4d8b-bf25-7f93cd41babd");

    }
}
